# Generated by Django 4.0.5 on 2022-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='depart',
            new_name='deptname',
        ),
    ]
